# Phiên bản Docker Compose
version: '3.8'

# Định nghĩa các dịch vụ (containers)
services:

  # --- ZooKeeper Ensemble (3 nodes) ---
  zookeeper1:
    image: zookeeper:3.8
    container_name: zookeeper1
    hostname: zookeeper1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: >-
        server.1=zookeeper1:2888:3888;2181
        server.2=zookeeper2:2888:3888;2181
        server.3=zookeeper3:2888:3888;2181
    volumes:
      - zookeeper1_data:/data # Lưu trữ dữ liệu (snapshot)
      - zookeeper1_log:/datalog # Lưu trữ transaction log
    networks:
      - kafka-net

  zookeeper2:
    image: zookeeper:3.8
    container_name: zookeeper2
    hostname: zookeeper2
    ports:
      - "2182:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: >-
        server.1=zookeeper1:2888:3888;2181
        server.2=zookeeper2:2888:3888;2181
        server.3=zookeeper3:2888:3888;2181
    volumes:
      - zookeeper2_data:/data
      - zookeeper2_log:/datalog
    networks:
      - kafka-net

  zookeeper3:
    image: zookeeper:3.8
    container_name: zookeeper3
    hostname: zookeeper3
    ports:
      - "2183:2181"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: >-
        server.1=zookeeper1:2888:3888;2181
        server.2=zookeeper2:2888:3888;2181
        server.3=zookeeper3:2888:3888;2181
    volumes:
      - zookeeper3_data:/data
      - zookeeper3_log:/datalog
    networks:
      - kafka-net

  # --- Kafka Brokers (3 nodes) ---
  kafka1:
    image: bitnami/kafka:3.6
    container_name: kafka1
    hostname: kafka1
    ports:
      - "9092:9092" # Port cho broker 1
    environment:
      KAFKA_BROKER_ID: 1 # ID duy nhất cho broker này
      # Kết nối tới ZooKeeper ensemble
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      # Cấu hình Listeners:
      # INTERNAL: Listener cho các container trong cùng docker network (sử dụng hostname:port)
      # EXTERNAL: Listener cho producer/consumer từ bên ngoài docker network (sử dụng host IP/hostname:mapped_port)
      KAFKA_LISTENERS: INTERNAL://kafka1:29092,EXTERNAL://0.0.0.0:9092
      # Cấu hình Advertised Listeners: Cách client nhìn thấy để kết nối
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:29092,EXTERNAL://${KAFKA_PUBLIC_IP}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL

      # Cấu hình số lượng bản sao mặc định (chuẩn cho ReID là 3)
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_CFG_MIN_INSYNC_REPLICAS: 2
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "false"
      # Tăng kích thước message tối đa cho phù hợp với feature vector hoặc dữ liệu ReID khác (mặc định 1MB)
      KAFKA_CFG_MESSAGE_MAX_BYTES: 5242880 # Ví dụ: 5MB (5 * 1024 * 1024)
      KAFKA_CFG_REPLICA_FETCH_MAX_BYTES: 5242880 # Replica cũng cần fetch message lớn
      KAFKA_CFG_LOG_DIRS: /bitnami/kafka/data/
    volumes:
      - kafka1_data:/bitnami/kafka/data # Lưu trữ dữ liệu log của Kafka
    networks:
      - kafka-net
    depends_on: # Khởi động sau khi ZooKeeper sẵn sàng
      - zookeeper1
      - zookeeper2
      - zookeeper3

  kafka2:
    image: bitnami/kafka:3.6
    container_name: kafka2
    hostname: kafka2
    ports:
      - "9093:9093" # Port cho broker 2
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      KAFKA_LISTENERS: INTERNAL://kafka2:29093,EXTERNAL://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:29093,EXTERNAL://${KAFKA_PUBLIC_IP}:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_CFG_MIN_INSYNC_REPLICAS: 2
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_CFG_MESSAGE_MAX_BYTES: 5242880
      KAFKA_CFG_REPLICA_FETCH_MAX_BYTES: 5242880
      KAFKA_CFG_LOG_DIRS: /bitnami/kafka/data/
    volumes:
      - kafka2_data:/bitnami/kafka/data
    networks:
      - kafka-net
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3

  kafka3:
    image: bitnami/kafka:3.6
    container_name: kafka3
    hostname: kafka3
    ports:
      - "9094:9094" # Port cho broker 3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      KAFKA_LISTENERS: INTERNAL://kafka3:29094,EXTERNAL://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka3:29094,EXTERNAL://${KAFKA_PUBLIC_IP}:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_CFG_MIN_INSYNC_REPLICAS: 2
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_CFG_MESSAGE_MAX_BYTES: 5242880
      KAFKA_CFG_REPLICA_FETCH_MAX_BYTES: 5242880
      KAFKA_CFG_LOG_DIRS: /bitnami/kafka/data/
    volumes:
      - kafka3_data:/bitnami/kafka/data
    networks:
      - kafka-net
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3

  # --- Kafka UI (Optional Management Tool) ---
  kafka-ui:
    image: provectuslabs/kafka-ui:latest # Giao diện quản lý Kafka
    container_name: kafka-ui
    ports:
      - "8080:8080" # Mở port 8080 để truy cập giao diện web
    environment:
      # Cấu hình kết nối tới Kafka cluster
      KAFKA_CLUSTERS_0_NAME: 'ReID Kafka Cluster'
      # Sử dụng Internal Listener để kết nối giữa Kafka UI và Brokers trong cùng network
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:29092,kafka2:29093,kafka3:29094
      # Cấu hình ZooKeeper (tùy chọn cho Kafka UI phiên bản mới)
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
    networks:
      - kafka-net
    depends_on: # Khởi động sau khi Kafka brokers sẵn sàng
      - kafka1
      - kafka2
      - kafka3

# Định nghĩa network nội bộ
networks:
  kafka-net:
    driver: bridge

# Định nghĩa Named Volumes để lưu trữ dữ liệu bền vững
volumes:
  zookeeper1_data:
  zookeeper1_log:
  zookeeper2_data:
  zookeeper2_log:
  zookeeper3_data:
  zookeeper3_log:
  kafka1_data:
  kafka2_data:
  kafka3_data: