version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: thesis-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      -  kafka-net
    restart: unless-stopped

volumes:
  redis_data:

networks:
  kafka-net:
    driver: bridge
